#!/bin/bash
# Builds VoiceType in release mode and assembles a self-contained .app bundle.
# Usage: ./package_app.sh [output_dir]   (defaults to ~/Downloads)
set -euo pipefail

cd "$(dirname "$0")"

OUT_DIR="${1:-$HOME/Downloads}"
PLIST=Sources/VoiceType/Resources/Info.plist
VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST")

# Auto-bump the build number every time so each packaged app is a distinct,
# non-overwriting file — otherwise VERSION never changes and this would just
# clobber the same VoiceType.<VERSION>.app on every run.
BUILD=$(( $(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST") + 1 ))
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD" "$PLIST"

APP="$OUT_DIR/VoiceType.$VERSION.$BUILD.app"
ARCH_DIR=".build/arm64-apple-macosx/release"

swift package resolve

# Patch KeyboardShortcuts to avoid the fatal `Bundle.module` trap when its
# resource bundle isn't at the .app root (see upstream issue:
# https://github.com/sindresorhus/KeyboardShortcuts/issues/231). The
# auto-generated Bundle.module accessor only checks Bundle.main.bundleURL
# (the .app root), which cannot hold a validly-signed resource per macOS
# codesign rules. This patches the one line in the vendored source that
# references Bundle.module to instead use Bundle.main.url(forResource:withExtension:),
# which correctly searches Contents/Resources.
patch_keyboard_shortcuts() {
    local util_path=".build/checkouts/KeyboardShortcuts/Sources/KeyboardShortcuts/Utilities.swift"
    if [[ ! -f "$util_path" ]]; then
        return
    fi
    chmod +w "$util_path"
    python3 - "$util_path" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text()
if ".keyboardShortcutsSafeBundle" in text:
    sys.exit(0)

text = text.replace(
    'NSLocalizedString(self, bundle: .module, comment: self)',
    'NSLocalizedString(self, bundle: .keyboardShortcutsSafeBundle, comment: self)',
)

inject = """
private extension Bundle {
    /// Safe lookup that avoids the fatal trap in the autogenerated `Bundle.module`
    /// when the resource bundle is not placed at the bundle root.
    static let keyboardShortcutsSafeBundle: Bundle = {
        #if os(macOS)
        if let url = Bundle.main.url(forResource: "KeyboardShortcuts_KeyboardShortcuts", withExtension: "bundle"),
           let bundle = Bundle(url: url) {
            return bundle
        }

        let rootURL = Bundle.main.bundleURL.appendingPathComponent("KeyboardShortcuts_KeyboardShortcuts.bundle")
        if let bundle = Bundle(url: rootURL) {
            return bundle
        }
        #endif

        let devURL = URL(fileURLWithPath: #file)
            .deletingLastPathComponent()  // Utilities.swift
            .deletingLastPathComponent()  // KeyboardShortcuts
            .deletingLastPathComponent()  // Sources
            .appendingPathComponent("KeyboardShortcuts_KeyboardShortcuts.bundle")
        if let bundle = Bundle(url: devURL) {
            return bundle
        }

        return Bundle.main
    }()
}
"""

marker = "}\n\n\nextension Data {"
if marker not in text:
    raise SystemExit("Marker not found in Utilities.swift; patch failed.")

text = text.replace(marker, "}\n\n" + inject + "\n\nextension Data {")
path.write_text(text)
PY
}

patch_keyboard_shortcuts

swift build -c release

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp "$ARCH_DIR/VoiceType" "$APP/Contents/MacOS/VoiceType"
cp Sources/VoiceType/Resources/Info.plist "$APP/Contents/Info.plist"
cp Sources/VoiceType/Resources/AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"
cp -R "$ARCH_DIR/KeyboardShortcuts_KeyboardShortcuts.bundle" "$APP/Contents/Resources/KeyboardShortcuts_KeyboardShortcuts.bundle"

# Verify the KeyboardShortcuts bundle was copied successfully and is non-empty
BUNDLE_PATH="$APP/Contents/Resources/KeyboardShortcuts_KeyboardShortcuts.bundle"
if ! [ -d "$BUNDLE_PATH" ]; then
    echo "ERROR: KeyboardShortcuts bundle directory not found at $BUNDLE_PATH" >&2
    exit 1
fi

if ! [ -n "$(find "$BUNDLE_PATH" -type f -print -quit)" ]; then
    echo "ERROR: KeyboardShortcuts bundle is empty at $BUNDLE_PATH" >&2
    exit 1
fi

# Copy Sparkle.framework into Contents/Frameworks
mkdir -p "$APP/Contents/Frameworks"
SPARKLE_FRAMEWORK=$(find .build/artifacts -iname "Sparkle.framework" -path "*macos*" | head -1)
if [[ -n "$SPARKLE_FRAMEWORK" ]]; then
    cp -R "$SPARKLE_FRAMEWORK" "$APP/Contents/Frameworks/"
fi

# Ad-hoc code signing (inside-out for nested executables)
if [[ -d "$APP/Contents/Frameworks/Sparkle.framework" ]]; then
    # Sign nested executables inside Sparkle.framework first (inside-out signing)
    find "$APP/Contents/Frameworks/Sparkle.framework" -type f -perm +111 -exec codesign --force -s - {} \;
    codesign --force -s - "$APP/Contents/Frameworks/Sparkle.framework"

    # Add rpath before signing the main app
    install_name_tool -add_rpath @executable_path/../Frameworks "$APP/Contents/MacOS/VoiceType"
fi

# Sign the main app last
codesign --force -s - "$APP"

# Warn if SUPublicEDKey is empty
PUBLIC_KEY=$(/usr/libexec/PlistBuddy -c "Print :SUPublicEDKey" "$PLIST" 2>/dev/null || echo "")
if [[ -z "$PUBLIC_KEY" ]]; then
    echo "WARNING: SUPublicEDKey is empty — this build cannot receive Sparkle auto-updates" >&2
fi

echo "Packaged $APP"
