#!/bin/bash
# Builds Yapboard in release mode, assembles a signed .app bundle, zips it,
# generates a Sparkle appcast, and publishes to GitHub Releases.
#
# Prerequisites:
#   - CFBundleShortVersionString in Info.plist set to the desired release version
#   - Sparkle EdDSA keypair already generated (run: generate_keys)
#   - Public key already set in SUPublicEDKey in Info.plist
#   - GitHub CLI (gh) installed and authenticated
#
# Usage: ./scripts/release.sh
set -euo pipefail

cd "$(dirname "$0")/.."

PLIST=Sources/Yapboard/Resources/Info.plist
VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$PLIST")

# Auto-bump CFBundleVersion (the internal build counter) for the release
BUILD=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$PLIST")
BUILD=$(( BUILD + 1 ))
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD" "$PLIST"

RELEASE_DIR="./release"
APP_NAME="Yapboard"
APP_BUNDLE="$APP_NAME.app"
ZIP_FILE="$RELEASE_DIR/$APP_NAME-$VERSION.zip"
APPCAST_FILE="$RELEASE_DIR/appcast.xml"

echo "==> Building Yapboard $VERSION"

# Verify Sparkle tools are available
GENERATE_APPCAST=$( { find .build -name "generate_appcast" -type f 2>/dev/null || true; } | head -1)
SIGN_UPDATE=$( { find .build -name "sign_update" -type f 2>/dev/null || true; } | head -1)

if [[ -z "$GENERATE_APPCAST" || -z "$SIGN_UPDATE" ]]; then
    echo "ERROR: Sparkle tools (generate_appcast, sign_update) not found in .build/" >&2
    echo "       Run 'swift build' first to resolve Sparkle's build artifacts." >&2
    exit 1
fi

echo "==> Using Sparkle tools:"
echo "    generate_appcast: $GENERATE_APPCAST"
echo "    sign_update: $SIGN_UPDATE"

# Patch KeyboardShortcuts to avoid the fatal `Bundle.module` trap when its
# resource bundle isn't at the .app root (see upstream issue:
# https://github.com/sindresorhus/KeyboardShortcuts/issues/231). The
# auto-generated Bundle.module accessor only checks Bundle.main.bundleURL
# (the .app root), which cannot hold a validly-signed resource per macOS
# codesign rules. This patches the one line in the vendored source that
# references Bundle.module to instead use Bundle.main.url(forResource:withExtension:),
# which correctly searches Contents/Resources.
patch_keyboard_shortcuts() {
    local util_path=".build/checkouts/KeyboardShortcuts/Sources/KeyboardShortcuts/Utilities.swift"
    if [[ ! -f "$util_path" ]]; then
        return
    fi
    chmod +w "$util_path"
    python3 - "$util_path" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text()
if ".keyboardShortcutsSafeBundle" in text:
    sys.exit(0)

text = text.replace(
    'NSLocalizedString(self, bundle: .module, comment: self)',
    'NSLocalizedString(self, bundle: .keyboardShortcutsSafeBundle, comment: self)',
)

inject = """
private extension Bundle {
    /// Safe lookup that avoids the fatal trap in the autogenerated `Bundle.module`
    /// when the resource bundle is not placed at the bundle root.
    static let keyboardShortcutsSafeBundle: Bundle = {
        #if os(macOS)
        if let url = Bundle.main.url(forResource: "KeyboardShortcuts_KeyboardShortcuts", withExtension: "bundle"),
           let bundle = Bundle(url: url) {
            return bundle
        }

        let rootURL = Bundle.main.bundleURL.appendingPathComponent("KeyboardShortcuts_KeyboardShortcuts.bundle")
        if let bundle = Bundle(url: rootURL) {
            return bundle
        }
        #endif

        let devURL = URL(fileURLWithPath: #file)
            .deletingLastPathComponent()  // Utilities.swift
            .deletingLastPathComponent()  // KeyboardShortcuts
            .deletingLastPathComponent()  // Sources
            .appendingPathComponent("KeyboardShortcuts_KeyboardShortcuts.bundle")
        if let bundle = Bundle(url: devURL) {
            return bundle
        }

        return Bundle.main
    }()
}
"""

marker = "}\n\n\nextension Data {"
if marker not in text:
    raise SystemExit("Marker not found in Utilities.swift; patch failed.")

text = text.replace(marker, "}\n\n" + inject + "\n\nextension Data {")
path.write_text(text)
PY
}

patch_keyboard_shortcuts

echo "==> Building with swift build -c release"
swift build -c release

ARCH_DIR=".build/arm64-apple-macosx/release"
APP_PATH="$ARCH_DIR/$APP_BUNDLE"

# Verify dSYM was produced
DSYM_PATH="$ARCH_DIR/Yapboard.dSYM"
if [[ ! -d "$DSYM_PATH" ]]; then
    echo "ERROR: dSYM not found at $DSYM_PATH" >&2
    echo "       Release builds should automatically produce dSYM files." >&2
    exit 1
fi

echo "==> Assembling .app bundle"
rm -rf "$APP_BUNDLE"
mkdir -p "$APP_BUNDLE/Contents/MacOS" "$APP_BUNDLE/Contents/Resources"

cp "$ARCH_DIR/Yapboard" "$APP_BUNDLE/Contents/MacOS/Yapboard"
cp Sources/Yapboard/Resources/Info.plist "$APP_BUNDLE/Contents/Info.plist"
cp Sources/Yapboard/Resources/AppIcon.icns "$APP_BUNDLE/Contents/Resources/AppIcon.icns"
cp -R "$ARCH_DIR/KeyboardShortcuts_KeyboardShortcuts.bundle" "$APP_BUNDLE/Contents/Resources/KeyboardShortcuts_KeyboardShortcuts.bundle"

# Verify the KeyboardShortcuts bundle was copied successfully and is non-empty
BUNDLE_PATH="$APP_BUNDLE/Contents/Resources/KeyboardShortcuts_KeyboardShortcuts.bundle"
if ! [ -d "$BUNDLE_PATH" ]; then
    echo "ERROR: KeyboardShortcuts bundle directory not found at $BUNDLE_PATH" >&2
    exit 1
fi

if ! [ -n "$(find "$BUNDLE_PATH" -type f -print -quit)" ]; then
    echo "ERROR: KeyboardShortcuts bundle is empty at $BUNDLE_PATH" >&2
    exit 1
fi

# Copy Sparkle.framework into Contents/Frameworks
mkdir -p "$APP_BUNDLE/Contents/Frameworks"
SPARKLE_FRAMEWORK=$(find .build/artifacts -iname "Sparkle.framework" -path "*macos*" | head -1)
if [[ -z "$SPARKLE_FRAMEWORK" ]]; then
    echo "ERROR: Sparkle.framework not found in .build/artifacts" >&2
    exit 1
fi
cp -R "$SPARKLE_FRAMEWORK" "$APP_BUNDLE/Contents/Frameworks/"

echo "==> Ad-hoc code signing (inside-out for nested executables)"
# Sign nested executables inside Sparkle.framework first (inside-out signing)
find "$APP_BUNDLE/Contents/Frameworks/Sparkle.framework" -type f -perm +111 -exec codesign --force -s - {} \;
codesign --force -s - "$APP_BUNDLE/Contents/Frameworks/Sparkle.framework"

# Add rpath before signing the main app
install_name_tool -add_rpath @executable_path/../Frameworks "$APP_BUNDLE/Contents/MacOS/Yapboard"

# Sign the main app last
codesign --force -s - "$APP_BUNDLE"

echo "==> Preparing release directory"
rm -rf "$RELEASE_DIR"
mkdir -p "$RELEASE_DIR"

echo "==> Archiving dSYM and binary for version $VERSION"
SYMBOLS_DIR="./release-symbols/$VERSION"
rm -rf "$SYMBOLS_DIR"
mkdir -p "$SYMBOLS_DIR"

# Copy the binary (post-signing) and dSYM to the symbols directory
cp "$APP_BUNDLE/Contents/MacOS/Yapboard" "$SYMBOLS_DIR/Yapboard"
cp -R "$DSYM_PATH" "$SYMBOLS_DIR/Yapboard.dSYM"

# Verify UUIDs match between binary and dSYM
BINARY_UUID=$(dwarfdump --uuid "$SYMBOLS_DIR/Yapboard" 2>/dev/null | head -1 | awk '{print $2}')
DSYM_UUID=$(dwarfdump --uuid "$SYMBOLS_DIR/Yapboard.dSYM" 2>/dev/null | head -1 | awk '{print $2}')

if [[ -z "$BINARY_UUID" || -z "$DSYM_UUID" ]]; then
    echo "ERROR: Could not extract UUID from binary or dSYM" >&2
    exit 1
fi

if [[ "$BINARY_UUID" != "$DSYM_UUID" ]]; then
    echo "ERROR: UUID mismatch between binary ($BINARY_UUID) and dSYM ($DSYM_UUID)" >&2
    exit 1
fi

echo "    Archived to: $SYMBOLS_DIR"
echo "    Binary UUID: $BINARY_UUID"
echo "    dSYM UUID:   $DSYM_UUID"

echo "==> Creating zip archive: $ZIP_FILE"
ditto -c -k --keepParent --sequesterRsrc "$APP_BUNDLE" "$ZIP_FILE"

echo "==> Generating Sparkle appcast"
# generate_appcast scans the zip files already in $RELEASE_DIR and writes/updates
# $RELEASE_DIR/appcast.xml itself (it does not print the appcast to stdout) — do
# NOT redirect its stdout to $APPCAST_FILE, that would truncate the very file the
# tool is about to write and race with it.
if ! "$GENERATE_APPCAST" --download-url-prefix "https://github.com/kirpalricky/yapboard/releases/download/v$VERSION/" "$RELEASE_DIR"; then
    echo "ERROR: generate_appcast failed." >&2
    exit 1
fi

if [[ ! -f "$APPCAST_FILE" ]]; then
    echo "ERROR: generate_appcast did not produce $APPCAST_FILE" >&2
    exit 1
fi

echo "==> Verifying SUPublicEDKey in Info.plist"
PUBLIC_KEY=$(/usr/libexec/PlistBuddy -c "Print :SUPublicEDKey" "$PLIST" 2>/dev/null || echo "")
if [[ -z "$PUBLIC_KEY" ]]; then
    echo "ERROR: SUPublicEDKey is not set in Info.plist" >&2
    echo "       Generate a keypair first by running: generate_keys" >&2
    echo "       (find it via: find .build -name generate_keys)" >&2
    exit 1
fi

echo "==> Publishing to GitHub Releases"
if gh release view "v$VERSION" > /dev/null 2>&1; then
    echo "    Release v$VERSION already exists, uploading new assets..."
    gh release upload "v$VERSION" "$ZIP_FILE" "$APPCAST_FILE" --clobber
else
    echo "    Creating new release v$VERSION..."
    gh release create "v$VERSION" "$ZIP_FILE" "$APPCAST_FILE" \
        --title "v$VERSION" \
        --generate-notes
fi

echo "==> Release complete!"
echo "    Zip: $ZIP_FILE"
echo "    Appcast: $APPCAST_FILE"
echo "    GitHub: https://github.com/kirpalricky/yapboard/releases/tag/v$VERSION"
